name: 'dbt_datamodeling'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_datamodeling:

    staging:
      +materialized: table

      stg_orders:
        +schema: silver
        +alias: stg_orders

    marts:
      +materialized: table